# Generated by Django 3.0.7 on 2020-06-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0032_auto_20200613_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamerules',
            options={'verbose_name': 'Ruleset'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='rules',
            new_name='_rules',
        ),
    ]
