# Generated by Django 3.0.7 on 2020-06-17 19:40

from django.db import migrations, models
import django.db.models.deletion

def algorithm_to_season_rules(apps, schema_editor):
    SeasonRules = apps.get_model('frisbeer', 'SeasonRules')
    Season = apps.get_model('frisbeer', 'Season')

    for season in Season.objects.all():
        name = season.get_score_algorithm_display()
        algorithm = season.score_algorithm
        season.rules, _ = SeasonRules.objects.get_or_create(name=name, score_algorithm=algorithm)
        season.save()


def season_rules_to_algorithm(apps, schema_editor):
    Season = apps.get_model('frisbeer', 'Season')
    for season in Season.objects.all():
        season.score_algorithm = season.rules.score_algorithm
        season.save()


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0033_auto_20200614_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elo_decay', models.BooleanField(default=True)),
                ('score_algorithm', models.CharField(choices=[('2017', 'Season 2017'), ('2018', 'Season 2018'), ('elo', 'Elo'), ('top_elo', 'Best elo')], default='elo', max_length=16)),
                ('rank_statistic', models.CharField(choices=[('RP', 'Rounds played'), ('RW', 'Rounds won'), ('GP', 'Games played'), ('GW', 'Games won')], default='RW', max_length=3)),
                ('rank_min_value', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='frisbeer.SeasonRules'),
        ),
        migrations.RunPython(
            algorithm_to_season_rules,
            season_rules_to_algorithm
        ),
        migrations.AlterField(
            model_name='season',
            name='game_rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frisbeer.GameRules'),
        ),
    ]
